{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-diff.fullname" . }}-metrics
  labels:
    {{- include "argo-diff.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "argo-diff.selectorLabels" . | nindent 4 }}
{{- end }}
